import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SwitchTheme } from "@/components/common/SwitchThemeButton";
import { CustomTabs, type TabProp, NonEmptyArray } from "@/components/common/CustomTabs";
import { CustomCard } from "@/components/common/CustomCard";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const TabProps: NonEmptyArray<TabProp> = [
    {
        tabName: "Home",
        tabLink: "/",
    },
    {
        tabName: "Work",
        tabLink: "/blog/tag/works",
    },
    {
        tabName: "About",
        tabLink: "/about",
    },
];

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased w-full grid-bg-light dark:grid-bg-dark grid grid-cols-3`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="col-span-1 flex flex-col gap-5 m-5">
                        <CustomCard title={"About"}>
                            <div>
                                <img src="" alt="" />
                                <h1>DEV活</h1>
                            </div>
                            <p></p>
                            <hr />
                        </CustomCard>
                        <CustomCard title={"Tag"}>a</CustomCard>
                        <CustomCard title={"Index"}>a</CustomCard>
                    </div>
                    <div className="col-span-2">
                        <div className="w-full border-b flex flex-row justify-between items-center ">
                            <div className="flex flex-row items-center gap-3">
                                <CustomTabs params={TabProps} />
                            </div>
                            <SwitchTheme />
                        </div>
                        <div className="container mx-auto my-5">{children}</div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
