import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { CustomSelect } from "@/components/common/CustomSelect";
import TheSchemaLogo from "@/components/common/TheSchemaLogo";
import { SwitchTheme } from "@/components/common/SwitchThemeButton";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <header className="h-auto flex flex-col w-screen items-start">
                        <div className="w-screen border flex flex-row justify-between items-center px-20">
                            <div className=" flex flex-row items-center">
                                <TheSchemaLogo />
                                <span>created By Ryok73</span>
                            </div>
                            <SwitchTheme />
                        </div>
                        <div className="ml-2 mt-2">
                            <CustomSelect tags={[""]} />
                        </div>
                    </header>
                    <div className="container mx-auto my-5">{children}</div>
                </ThemeProvider>
            </body>
        </html>
    );
}
